const UserModel = require('../models/UserModel')
const PostModel = require('../models/PostModel')
const FollowerModel = require('../models/FollowerModel')
const ProfileModel = require('../models/ProfileModel')
const bcrypt = require('bcryptjs')